trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'your-subscription-name'
  appServiceName: 'KM-APPS'
  resourceGroupName: 'KM-RG-NE'
  location: 'northeurope'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration Release'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: DeploymentJob
    displayName: Deploy job
    pool:
      vmImage: 'ubuntu-latest'
    environment:
      name: 'km-dev'
      resourceType: 'VirtualMachine'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: km-apps'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(appServiceName)'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              resourceGroupName: '$(resourceGroupName)'
              slotName: 'production'

